[project]
name = "multi-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=1.9.3",
    "crewai-tools>=1.9.3",
    "langchain-openai>=0.3.23",
    "requests>=2.32.5",
]
